package local.oss.chronicle.data.local

import local.oss.chronicle.data.model.Chapter
import org.hamcrest.MatcherAssert.assertThat
import org.hamcrest.Matchers.`is`
import org.junit.Test

/**
 * Tests for Chapter model focusing on the primary key fix.
 *
 * This test verifies the fix for the chapter primary key conflict where multiple chapters
 * from the same track share the same `id` (the track's rating key).
 *
 * The fix uses auto-generated `uid` as the primary key instead of `id`.
 */
class ChapterPrimaryKeyTest {
    @Test
    fun `multiple chapters with same id can be created with different indexes`() {
        // GIVEN: Multiple chapters from the same track (all have id=471, the track's rating key)
        val trackId = "plex:471"
        val bookId = "plex:12345"

        // WHEN: We create 8 chapters with the same id but different indexes
        val chapters =
            (1..8).map { index ->
                Chapter(
                    uid = 0L, // Will be auto-generated by Room on insert
                    title = "Chapter $index",
                    id = 471L, // Same ID for all chapters (track's rating key)
                    index = index.toLong(),
                    startTimeOffset = (index - 1) * 1000L,
                    endTimeOffset = index * 1000L,
                    trackId = trackId,
                    bookId = bookId,
                )
            }

        // THEN: All chapters should be created successfully with the same id
        assertThat("Should create 8 chapters", chapters.size, `is`(8))

        // Verify each chapter has the correct data
        chapters.forEachIndexed { i, chapter ->
            assertThat("Chapter ${i + 1} has same id", chapter.id, `is`(471L))
            assertThat("Chapter ${i + 1} has different index", chapter.index, `is`((i + 1).toLong()))
            assertThat("Chapter ${i + 1} has correct trackId", chapter.trackId, `is`(trackId))
            assertThat("Chapter ${i + 1} has correct bookId", chapter.bookId, `is`(bookId))
        }
    }

    @Test
    fun `chapters are created with correct bookId`() {
        // GIVEN: A specific book ID
        val bookId = "plex:98765"
        val trackId = "plex:100"

        // WHEN: Creating chapters with that book ID
        val chapter1 =
            Chapter(
                uid = 0L,
                title = "Chapter 1",
                id = 100L,
                index = 1L,
                startTimeOffset = 0L,
                endTimeOffset = 1000L,
                trackId = trackId,
                bookId = bookId,
            )

        val chapter2 =
            Chapter(
                uid = 0L,
                title = "Chapter 2",
                id = 100L,
                index = 2L,
                startTimeOffset = 1000L,
                endTimeOffset = 2000L,
                trackId = trackId,
                bookId = bookId,
            )

        // THEN: Chapters should have the correct bookId
        assertThat("Chapter 1 has correct bookId", chapter1.bookId, `is`(bookId))
        assertThat("Chapter 2 has correct bookId", chapter2.bookId, `is`(bookId))
    }

    @Test
    fun `uid defaults to zero for new chapters`() {
        // GIVEN: A new chapter
        val chapter =
            Chapter(
                uid = 0L,
                title = "Test Chapter",
                id = 500L,
                index = 1L,
                startTimeOffset = 0L,
                endTimeOffset = 1000L,
                trackId = "plex:500",
                bookId = "plex:1",
            )

        // THEN: The uid should default to 0 before database insertion
        assertThat("UID defaults to 0 for new chapters", chapter.uid, `is`(0L))
    }
}
